version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_app
    volumes:
      - .:/app  # Mount the project folder to the container
    ports:
      - "8000:8000"
    networks:
      - webnet

  nginx:
    #build:
      #context: .
      #dockerfile: Dockerfile.nginx
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - webnet


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # command: 
    #          certonly --reinstall --webroot --webroot-path=/var/www/certbot
    #          --email eslamelhadedy50@gmail.com --agree-tos --no-eff-email
    #          -d vipapi.cyparta.com

    #command: certonly --standalone --non-interactive --email my@email.com --agree-tos --preferred-challenges http --dry-run -d my.domain.com
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
