version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_app
    ports:
      - "8000:8000"
    networks:
      - webnet
    # environment:
    #   # Environment variables (Add if needed)
   

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      #- ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - webnet


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
