version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this matches the actual file name
    image: django_app:latest  # Explicitly set the image name and tag
    container_name: django_app
    ports:
      - "8000:8000"
    # env_file:
    #   - /root/.env
    networks:
      - webnet

  nginx:
    build:
        context: .
        dockerfile: Dockerfile.nginx  # Ensure this matches the actual file name
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    networks:
      - webnet
    depends_on:
      - django

networks:
  webnet:
