# Dockerfile.nginx
FROM nginx:latest

# Copy custom Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d


# Optional: Copy SSL certificates if you use HTTPS
# COPY certs /etc/ssl/certs

# Optional: Set environment variables if needed
# ENV NGINX_ENV=production

# Expose ports
EXPOSE 80 443

# Default command
CMD ["nginx", "-g", "daemon off;"]
