version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_app
    volumes:
      - .:/app  # Mount the project folder to the container
    ports:
      - "8000:8000"
    networks:
      - webnet


#ddxxxxssssss
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email eslamelhadedy50@gmail.com --agree-tos --no-eff-email --force-renewal --non-interactive -d memo.cyparta.com 
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
    networks:
      - webnet
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./scripts:/scripts
    ports:
      - "80:80"
      - "443:443"
    restart: always
    #command: /bin/bash -c "chmod +x /scripts/check_and_enable_ssl.sh && /scripts/check_and_enable_ssl.sh && nginx -g 'daemon off;'"
    #command: /bin/bash -c "/scripts/check_and_enable_ssl.sh && nginx -g 'daemon off;'"
    #command: /bin/bash -c "nginx -g 'daemon off;' && /scripts/enable_ssl.sh"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
