# Generated by Django 4.2.7 on 2024-02-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllTypeModel',
            fields=[
                ('auto_slug_field', models.SlugField(auto_created=True)),
                ('big_integer_field', models.BigIntegerField()),
                ('boolean_field', models.BooleanField(null=True)),
                ('char_field', models.CharField(max_length=100)),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_field', models.DurationField()),
                ('email_field', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='files/')),
                ('float_field', models.FloatField()),
                ('image_field', models.ImageField(upload_to='images/')),
                ('integer_field', models.IntegerField()),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('positive_big_integer_field', models.PositiveBigIntegerField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('small_auto_field', models.SmallAutoField(primary_key=True, serialize=False)),
                ('small_integer_field', models.SmallIntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
                ('json_field', models.JSONField()),
                ('file_path_field', models.FilePathField(path='/path/to/dir/')),
                ('decimal_range_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('float_range_field', models.FloatField()),
                ('integer_range_field', models.IntegerField()),
                ('foreign_key_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_set', to='vipadmin.othermodel')),
                ('many_to_many_field', models.ManyToManyField(related_name='many_to_many_set', to='vipadmin.othermodel')),
                ('one_to_one_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one', to='vipadmin.othermodel')),
            ],
        ),
    ]
