# Generated by Django 4.2.7 on 2024-02-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0002_remove_alltypemodel_decimal_range_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
    ]
