# Generated by Django 4.2.7 on 2024-02-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0003_globalmodelregistry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalModelRegistry',
        ),
    ]
