# Generated by Django 4.2.7 on 2024-02-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0005_alter_alltypemodel_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltypemodel',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
