# Generated by Django 4.2.7 on 2024-03-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0007_alter_alltypemodel_time_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltypemodel',
            name='file_path_field',
        ),
    ]
