# Generated by Django 4.2.7 on 2024-03-20 23:05

import CypartaGraphqlSubscriptionsTools.mixins
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vipadmin', '0009_lifecyclegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifecycleGroup',
        ),
        migrations.CreateModel(
            name='LifecycleGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, 'auth.group'),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
