# Generated by Django 4.2.7 on 2024-03-20 23:07

import CypartaGraphqlSubscriptionsTools.mixins
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vipadmin', '0010_delete_lifecyclegroup_lifecyclegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifecycleGroup',
        ),
        migrations.CreateModel(
            name='LifecycleGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, 'auth.group'),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
