# Generated by Django 4.2.7 on 2024-03-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0011_delete_lifecyclegroup_lifecyclegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifecyclegroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
