# Generated by Django 4.2.7 on 2024-03-21 22:53

import CypartaGraphqlSubscriptionsTools.mixins
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vipadmin', '0012_alter_lifecyclegroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='lifecyclegroup',
            options={},
        ),
    ]
