# Generated by Django 4.2.7 on 2024-04-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0013_lifecycleuser_alter_lifecyclegroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltypemodel',
            name='choice_filed',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank'), ('CRYPTO', 'Crypto')], max_length=100, null=True),
        ),
    ]
