# Generated by Django 4.2.7 on 2024-04-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0014_alltypemodel_choice_filed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltypemodel',
            name='choice_filed',
            field=models.CharField(blank=True, choices=[('F', 'Fiction'), ('NF', 'Non-Fiction'), ('SF', 'Science Fiction')], max_length=100, null=True),
        ),
    ]
