# Generated by Django 4.2.7 on 2024-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0015_alter_alltypemodel_choice_filed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltypemodel',
            name='choice_filed2',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank'), ('CRYPTO', 'Crypto')], max_length=100, null=True),
        ),
    ]
