# Generated by Django 4.2.7 on 2024-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0016_alltypemodel_choice_filed2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltypemodel',
            name='char_field',
            field=models.CharField(default='ahmed', max_length=100),
        ),
    ]
