# Generated by Django 4.2.7 on 2024-04-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0017_alter_alltypemodel_char_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltypemodel',
            name='choice_filed2',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank'), ('CRYPTO', 'Crypto')], editable=False, max_length=100, null=True),
        ),
    ]
