# Generated by Django 4.2.7 on 2024-04-04 01:00

import CypartaGraphqlSubscriptionsTools.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0018_alter_alltypemodel_choice_filed2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salay', models.FloatField()),
            ],
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, models.Model),
        ),
    ]
