# Generated by Django 4.2.7 on 2024-04-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0019_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='name of employee', max_length=100),
        ),
    ]
