# Generated by Django 4.2.7 on 2024-04-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0020_alter_employee_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alltypemodel',
            options={'verbose_name': 'AllTypeModel', 'verbose_name_plural': 'AllTypeModel'},
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='auto_slug_field',
            field=models.SlugField(auto_created=True, verbose_name='Auto Slug Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='big_integer_field',
            field=models.BigIntegerField(verbose_name='Big Integer Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='boolean_field',
            field=models.BooleanField(null=True, verbose_name='Boolean Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='char_field',
            field=models.CharField(default='ahmed', max_length=100, verbose_name='Character Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='date_field',
            field=models.DateField(verbose_name='Date Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='datetime_field',
            field=models.DateTimeField(verbose_name='Datetime Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Decimal Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='duration_field',
            field=models.DurationField(verbose_name='Duration Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='email_field',
            field=models.EmailField(max_length=254, verbose_name='Email Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='file_field',
            field=models.FileField(upload_to='files/', verbose_name='File Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='float_field',
            field=models.FloatField(verbose_name='Float Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='foreign_key_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_set', to='vipadmin.othermodel', verbose_name='Foreign Key Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(verbose_name='Generic IP Address Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='image_field',
            field=models.ImageField(upload_to='images/', verbose_name='Image Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='integer_field',
            field=models.IntegerField(verbose_name='Integer Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='json_field',
            field=models.JSONField(verbose_name='JSON Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='many_to_many_field',
            field=models.ManyToManyField(related_name='many_to_many_set', to='vipadmin.othermodel', verbose_name='Many-to-Many Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='one_to_one_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one', to='vipadmin.othermodel', verbose_name='One-to-One Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(verbose_name='Positive Big Integer Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='positive_integer_field',
            field=models.PositiveIntegerField(verbose_name='Positive Integer Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='positive_small_integer_field',
            field=models.PositiveSmallIntegerField(verbose_name='Positive Small Integer Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='slug_field',
            field=models.SlugField(verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='small_auto_field',
            field=models.SmallAutoField(primary_key=True, serialize=False, verbose_name='Small Auto Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='small_integer_field',
            field=models.SmallIntegerField(verbose_name='Small Integer Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='text_field',
            field=models.TextField(blank=True, null=True, verbose_name='Text Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='time_field',
            field=models.TimeField(blank=True, verbose_name='Time Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='url_field',
            field=models.URLField(verbose_name='URL Field'),
        ),
        migrations.AlterField(
            model_name='alltypemodel',
            name='uuid_field',
            field=models.UUIDField(verbose_name='UUID Field'),
        ),
    ]
