# Generated by Django 4.2.7 on 2024-04-07 01:38

import CypartaGraphqlSubscriptionsTools.mixins
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vipadmin', '0021_alter_alltypemodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LifecycleGroup',
        ),
        migrations.DeleteModel(
            name='LifecycleUser',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, 'auth.group'),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
