# Generated by Django 4.2.7 on 2024-04-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0024_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermodel',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_foreign_key_set', to='vipadmin.employee', verbose_name='Employee_Foreign Key Field'),
        ),
    ]
