# Generated by Django 4.2.7 on 2024-08-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0025_othermodel_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltypemodel',
            name='boolean_field2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Boolean Field'),
        ),
    ]
