# Generated by Django 4.2.7 on 2024-08-15 17:38

import CypartaGraphqlSubscriptionsTools.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0026_alltypemodel_boolean_field2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(default='ssss', max_length=100, verbose_name='Character Field')),
                ('file_field', models.FileField(upload_to='files/', verbose_name='File Field')),
            ],
            bases=(CypartaGraphqlSubscriptionsTools.mixins.CypartaSubscriptionModelMixin, models.Model),
        ),
    ]
