# Generated by Django 4.2.7 on 2024-08-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0028_delete_testmodel_employee_file_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='file_field',
            new_name='image',
        ),
    ]
