# Generated by Django 4.2.7 on 2024-08-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0029_rename_file_field_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field'),
        ),
    ]
