# Generated by Django 4.2.7 on 2024-08-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0031_employee_image1_employee_image2_employee_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image3',
        ),
    ]
