# Generated by Django 4.2.7 on 2024-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0032_remove_employee_image1_remove_employee_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field'),
        ),
    ]
