# Generated by Django 4.2.7 on 2024-08-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0033_employee_image1_employee_image2_employee_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltypemodel',
            name='choice_filed2',
        ),
    ]
