# Generated by Django 4.2.7 on 2024-08-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0035_alltypemodel_many_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='many_users',
            field=models.ManyToManyField(related_name='many_to_many_users_set', to='vipadmin.user', verbose_name='Many-to-Many users Field'),
        ),
    ]
