# Generated by Django 4.2.7 on 2024-09-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipadmin', '0036_employee_many_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltypemodel',
            name='text_field',
            field=models.TextField(blank=True, default=1, verbose_name='Text Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field3'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='imag Field4'),
        ),
    ]
