name: Django CI/CD with Uvicorn (No Docker Hub)

on:
  push:
    branches:
      - main

env:
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}  # GitHub Actions variable for the domain name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo snap install docker

      - name: Build Docker Image
        run: |
          # Use the DOMAIN_NAME environment variable for building Docker images
          DOMAIN_NAME=${{ vars.DOMAIN_NAME }} docker compose build
          docker images  # Confirm the build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Droplet and Clone Project
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            # Install Git if not installed
            sudo apt-get update && sudo apt-get install -y git

            # Set up GitHub authentication using GitHub Token
            git config --global credential.helper 'store --file=/root/.git-credentials'
            echo "https://${{ github.token }}:@github.com" > /root/.git-credentials

            # Dynamically get repository name and branch
            REPO_NAME=$(basename -s .git https://github.com/${{ github.repository }})
            REPO_URL=https://github.com/${{ github.repository }}
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')

            # Clone the project repository into a directory named after the repo
            if [ ! -d "/root/$REPO_NAME" ]; then
              git clone --branch $BRANCH_NAME $REPO_URL /root/$REPO_NAME
            else
              cd /root/$REPO_NAME && git pull origin $BRANCH_NAME
            fi 

      - name: Replace DOMAIN_NAME in NGINX Configs
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            # Navigate to the project directory
            cd /root/$REPO_NAME
            # Print the current working directory
            echo "Current directory is: $(pwd)"

            # List the contents of the current directory
            echo "Listing project directory contents:"
            echo "$(ls -la)"

            # Replace the placeholder {{DOMAIN_NAME}} with the actual domain name in NGINX configs
            sed -i "s/{{DOMAIN_NAME}}/${{ vars.DOMAIN_NAME }}/g" nginx/conf/default.conf
            sed -i "s/{{DOMAIN_NAME}}/${{ vars.DOMAIN_NAME }}/g" nginx/conf/ssl.conf

            # Move the updated template files to their final locations
            cp nginx/conf/default.conf nginx/conf/default.conf
            cp nginx/conf/ssl.conf nginx/conf/ssl.conf

      - name: Deploy via SSH and Run Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            # Load environment variables from .env file
            export $(grep -v '^#' /root/.env | xargs)

            # Navigate to the project directory
            cd /root/$REPO_NAME

            # Bring down any existing containers
            DOMAIN_NAME=${{ vars.DOMAIN_NAME }} docker-compose down || true

            # Build and start containers with the updated configuration
            DOMAIN_NAME=${{ vars.DOMAIN_NAME }} docker-compose up -d --build

            # Force exit to close the SSH session
            exit 0
